{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '0.0.10', 'description': 'An app to view netCDF files hosted on a THREDDS Data Server', 'long_description': '', 'keywords': 'netCDF', 'author': 'Enoch Jones', 'author_email': 'jon.enoch.jones@gmail.com', 'url': 'https://github.com/BYU-Hydroinformatics/tethysapp-netcdfviewer', 'license': ''}"
  dev_url: {{ data.get('url') }}

outputs:
  - name: {{ name }}

extra:
  author_email:  {{ data.get('author_email')}}
  keywords: {{ data.get('keywords')}}
  recipe-maintainers:
    - TethysAppWarehouse
build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - pandas
  - requests
  - siphon
  - netCDF4
  - numpy
source:
  path: ..
